### ISSUE TITLE
안녕하세요 소스를 다운받아 import했는데 ㅠㅠ 

### ISSUE THREAD

**Issue by yangbongsoo** [keesun/amugona#1]
안녕하세요 방송을 통해서 spring boot 공부하고 있는 대학생입니다. 

![default](https://cloud.githubusercontent.com/assets/7060510/9705460/65c8bdbe-5500-11e5-8213-4db909e6bd41.PNG)
소스를 다운받아서 import했는데 setJoined, setUpdated 부분이 인식이 안되더라구요. 

제가 JDK1.7인데 pom.xml의 자바버전은 1.8입니다. 그래서 인식 못하는 문제일까요??

**Comment by keesun** [comment]
안녕하세요.

IntelliJ -> Settings -> Plugins 가셔서 Lombok 플러그인 설치해 주셔야해요.

http://blog.woniper.net/229

여기에 설명이 있네요.

**Comment by keesun** [comment]
> 제가 JDK1.7인데 pom.xml의 자바버전은 1.8입니다.

이 부분은 롬복과 별개로 문제가 될 수 있으니 1.8 JDK도 설치하시고 IntelliJ의 JDK 메뉴에 추가해 주세요.

**Comment by yangbongsoo** [comment]
오 해결되었습니다 감사합니다.
