### ISSUE TITLE
두번째강의 1시간9분 대 설명에 대한 질문이요 

### ISSUE THREAD

**Issue by yangbongsoo** [keesun/amugona#2]
안녕하세요 궁금한것이 생겼는데 어디다 질문해야 될지 잘 몰라서 여기에 글을 씁니다. ㅎㅎ

제가 두번째 강의 리뷰하면서 복습하고 있는데 
1. 테스트에  @Transactional에 붙으면 자동으로 롤백이 된다고 말씀하셨는데 제가 아는 롤백이란 개념은 
   '데이터베이스에서 업데이트에 오류가 발생할 때, 이전 상태로 되돌리는 것' 인데 테스트에서 롤백이 된다라는 부분이 잘 와닿지 않습니다. 
2. 테스트에 붙은 @Transactional 과 서비스에 있는 @Transactional과 정확히 어떤 차이가 있는건가요?

답변해주시면 정말 감사드리겠습니다 ㅎㅎ

**Comment by keesun** [comment]
좀이따 방송에서 구두로 설명 드릴께요.

—
Keesun Baik백기선

**Comment by keesun** [comment]
@yangbongsoo 방송에서 설명 드렸어요~
