### ISSUE TITLE
시큐리티 질문.

### ISSUE THREAD

**Issue by stkang** [keesun/amugona#5]
안녕하세요.

방송중에도 비슷한 질문을 했는데요.

httpBasic이 해당 계정으로 로그인을 미리 하여
권한을 취득하고 해당 페이지 접근을 가능하게 해주는것인가요?

**Comment by keesun** [comment]
HTTP Basic 인증 방식에 대해 이해하신다면 좀 더 이해하기 쉬운데요.

우선 `httpBasic()` 메서드는 HTTP Basic 인증 방식이 사용하는 HTTP 요청 헤더를 추가해주는 메서드입니다.

그 헤더값이 있으면 로그인 한것으로 가정하는거죠.
또 그 헤더에는 사용자의 username과 password가 들어있기 때문에 현재 사용자가 누구며 어떤 권한을 가진 유저인지도 알 수 있죠.

가장 쉬운 인증 방식이지만 보안상 많이 취약해요.

**Comment by kevin-lee** [comment]
@stkang 아주 약간 첨언하자면,
기선님께서 말씀하신대로, HTTP header에 사용자 username과 password를 매 request마다 넣어서 전송하는 방식으로 로그아웃도 안 되고, 매 request마다 header에 사용자 로그인 정보가 노출되어 실제 서비스나 웹앱에는 사용을 권장하지 않는 방법입니다. 부득이하게 쓰시게 되더라도 https와 함께 쓰셔야겠죠. (쓰지 마세요! ㅠ_ㅠ)

자세한 설명은 여기를 https://en.wikipedia.org/wiki/Basic_access_authentication 참조 하시구요.
